
# Note: This crate must be built using do.sh

[package]
name = "evm-loader"
version = "2.0.8"
description = "Ethereum VM loader"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2018"
exclude = ["js/**"]

[features]
no-entrypoint = []
program = ["solana-sdk/program"]
default = ["solana-sdk/default"]

[dependencies]
num-derive = "0.3"
num-traits = "0.2"
remove_dir_all = "=0.5.0"
solana-sdk = { version = "1.3.17", default-features = false, optional = true }
thiserror = "1.0"
arrayref = "0.3.6"
num_enum = "0.5.1"
primitive-types = { version = "0.7", default-features = false }
evm = { path = "../rust-evm", version = "0.18.0", default_features = false }
hex = "0.4.2"
bs58 = "0.3.1"
sha3 = { version = "0.8", default-features = false }

[dev-dependencies]
rand = { version = "0.7.0"}

[lib]
crate-type = ["cdylib", "lib"]
