
# Note: This crate must be built using cargo build-bpf

[package]
name = "evm-loader"
version = "2.0.8"
description = "Ethereum VM loader"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2018"
exclude = ["js/**"]

[features]
evm_debug = []
no-entrypoint = []
test-bpf = []
custom-heap = []
default = ["custom-heap", "evm_debug"]

[dependencies]
solana-program = { version = "1.6.4", default_features = false }
num-derive = "0.3"
num-traits = "0.2"
remove_dir_all = "=0.5.0"
thiserror = "1.0"
arrayref = "0.3.6"
num_enum = "0.5.1"
primitive-types = { version = "0.7", default-features = false, features = ["serde_no_std"] }
evm = { path = "../rust-evm", version = "0.18.0", default_features = false, features = ["with-serde"] }
hex = "0.4.2"
bs58 = "0.3.1"
sha3 = { version = "0.8", default-features = false }
getrandom = { version = "0.1.16", default_features = false, features = ["dummy"] }
#k256 = { version = "0.4.0", default-features = false, features = ["ecdsa"] }
libsecp256k1 = { version = "0.3.5", default-features = false }
serde = "1.0.112"
serde_bytes = "0.11"
serde_derive = "1.0.103"
impl-serde = "0.1"
rlp = "0.4"
bincode = ""
evm-runtime = { version = "0.18", path = "../rust-evm/runtime", default-features = false }

[dev-dependencies]
rand = { version = "0.7.0"}
solana-program-test = "1.6.4"
solana-sdk = "1.6.4"

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
